version: '3.4'

services:
  dotnet6dockerize.clientapp:
    image: ${DOCKER_REGISTRY-}dotnet6dockerizeclientapp
    build:
      context: .
      dockerfile: dotnet6Dockerize.ClientApp/Dockerfile

  dotnet6dockerize.webapi:
    image: ${DOCKER_REGISTRY-}dotnet6dockerizewebapi
    build:
      context: .
      dockerfile: dotnet6Dockerize.WebAPI/Dockerfile